[package]
name = "print-billing"
version = "0.1.0"
edition = "2021"

[lib]
name = "print_billing_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }

[profile.dev]
incremental = false
codegen-units = 1

[profile.dev.package."*"]
incremental = false
codegen-units = 1

[profile.dev.build-override]
incremental = false
codegen-units = 1

