/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1c",
        "surface-container": "#202020",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "primary": "#a3c9ff",
        "primary-container": "#0078d4",
        "on-primary": "#00315c",
        "on-primary-container": "#ffffff",
        "secondary": "#c8c6c6",
        "secondary-container": "#474747",
        "on-secondary-container": "#b6b5b4",
        "tertiary": "#ffb689",
        "tertiary-container": "#bc5b00",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c0c7d4",
        "outline": "#8a919e",
        "outline-variant": "#404752",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc7fd',
          400: '#36a9fa',
          500: '#0c8de9',
          600: '#006fc7',
          700: '#0159a3',
          800: '#054b86',
          900: '#0a3f6f',
          950: '#072849',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        code: ['"JetBrains Mono"', 'monospace'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
}
